version: '3'

services:

  postgres:
    image: postgres
    ports: 
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres

  supertokens:
    image: registry.supertokens.io/supertokens/supertokens-postgresql